export const lightTheme = {
  cardBg: '#fdb515',
  cardText: 'white',
  cardBorder: '#ffffffff',
  labelBg: 'rgba(54, 44, 14, 0.8)',
  acronymBg: '#a67a05',
  acronymText: 'white',
  buttonBg: 'rgba(59, 59, 59, 1)',
  buttonText: 'white',
  buttonHoverBg: '#a67a05',
  buttonHoverText: 'white',
  buttonHoverBorder: '#a07707ff',
  helpMenuBg: 'white',
  helpMenuText: 'black',
  linkText: '#007bff',
  toggleButtonBg: '#cececeff',
  toggleButtonText: 'white',
  toggleButtonHover: '#0056b3',
  closeButtonText: 'black',
  routePlannerText: 'black',
  routePlannerBg: '#F5F5F5',
  startIconColor: 'black',
  searchBarInputBg: '#c7c8ca',
  searchBarInputColor: 'black',
  searchBarButtonBg: '#e4e4e4ff',
  searchBarButtonText: 'black',
  searchBarButtonHover: '#fdb515'
};

export const darkTheme = {
  cardBg: '#2c2c2c',
  cardText: '#f0f0f0',
  cardBorder: '#1a1a1aff',
  labelBg: 'rgba(0, 0, 0, 0.7)',
  acronymBg: '#a07707ff',
  acronymText: '#f0f0f0',
  buttonBg: '#444444',
  buttonText: '#f0f0f0',
  buttonHoverBg: '#a67a05',
  buttonHoverText: '#ffffff',
  buttonHoverBorder: '#a07707ff',
  helpMenuBg: '#2c2c2c',
  helpMenuText: 'white',
  linkText: '#fdb515',
  toggleButtonBg: '#a67a05',
  toggleButtonText: 'black',
  toggleButtonHover: '#fdb515',
  closeButtonText: 'white',
  routePlannerText: 'white',
  routePlannerBg: '#1a1a1aff',
  startIconColor: '#fdb515',
  searchBarInputBg: '#080808ff',
  searchBarInputColor: 'white',
  searchBarButtonBg: '#fdb515',
  searchBarButtonText: 'white',
  searchBarButtonHover: '#f0f0f0ff',
  searchBarButtonHoverText: '#000000ff'
};
